apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-ingress
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/version: 3.3.0
    helm.sh/chart: nginx-ingress-1.0.0
  name: nginx-ingress-controller
  namespace: default
  resourceVersion: "614556"
  uid: e5afa433-411e-44e2-a105-c45e6f78ed6b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.3.152
  clusterIPs:
  - 10.102.3.152
  externalTrafficPolicy: Local
  healthCheckNodePort: 32627
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31325
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30926
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
