apiVersion: v1
kind: Pod
metadata:
  name: www-b
  labels:
    name: www
spec:
  containers:
  - name: www-b
    image: nginx:alpine
    ports:
      - containerPort: 80
        name: www-b
    volumeMounts:
      - name: www-persistent-storage
        mountPath: /usr/share/nginx/html
  volumes:
    - name: www-persistent-storage
      persistentVolumeClaim:
        claimName: my-claim
