apiVersion: v1
kind: Service
metadata:
  name: node-port
  annotations:
spec:
  internalTrafficPolicy: Cluster
  selector:
    name: www
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
status:
  loadBalancer: {} 
