apiVersion: v1
kind: Pod
metadata:
  name: www-a
  labels:
    name: www
spec:
  containers:
  - name: www-a
    image: nginx:alpine
    envFrom:
    - configMapRef:
        name: env-var
    ports:
      - containerPort: 80
        name: www-a
    volumeMounts:
      - name: www-persistent-storage
        mountPath: /usr/share/nginx/html
  volumes:
    - name: www-persistent-storage
      persistentVolumeClaim:
        claimName: my-claim
